include $(MODULE_ROOT)/../android-rpcservice/FuncCfg.mk

include $(MODULE_ROOT)/Config.mk

SRCDIR = ../src

SRCS := xds.c \
    xds_608.c \
    xds_708.c

#SRCS = $(notdir $(wildcard ./src/*.c))

COMP=xds

include $(MODULE_ROOT)/common.mak

clean: common_clean

module_clean:

